version: "3.7"

services:
  point-authentication-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${BACK_CONTAINER_NAME}
    ports:
      - 3002:3002
      - 4002:4002
    volumes:
      - service:/authentication
    networks:
      - point-authentication-network
volumes:
  service:
networks:
  point-authentication-network:
    name: point-network
