apiVersion: v1
kind: Service
metadata:
  name: thl-khoaluan-auth-svc
spec:
  selector:
    app: thl-khoaluan-qldrl
  ports:
    - port: 80
      targetPort: 3002
      protocol: TCP
      name: http
  type: LoadBalancer
